name: swervpay_dart
description: Dart Client for Swervpay. API Wrapper for everything that Swervpay offer for Flutter/Dart Developer.
version: 0.0.4
homepage: https://docs.swervpay.co/sdks/dart
repository: https://github.com/swerv-ltd/swervpay-dart
issue_tracker: https://github.com/swerv-ltd/swervpay-dart/issues
documentation: https://docs.swervpay.co/sdks/dart
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.25.2
  very_good_analysis: ^5.0.0+1
